# Generated by Django 6.0.2 on 2026-02-23 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Document batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('combined_summary', models.TextField(blank=True, help_text='AI-generated summary combining all documents in the batch', null=True)),
                ('key_insights', models.JSONField(blank=True, help_text='Key insights extracted across all documents', null=True)),
                ('contradictions', models.JSONField(blank=True, help_text='Contradictions or inconsistencies found across documents', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='documents.documentbatch')),
            ],
            options={
                'verbose_name_plural': 'Batch analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The batch / analysis session this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentbatch'),
        ),
        migrations.AddIndex(
            model_name='documentbatch',
            index=models.Index(fields=['user', '-created_at'], name='documents_d_user_id_c68f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbatch',
            index=models.Index(fields=['status'], name='documents_d_status_05fad4_idx'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='documents.documentbatch'),
        ),
    ]