# Generated by Django 5.2.6 on 2025-09-09 11:19

import django.core.validators
import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#007bff", help_text="Hex color code", max_length=7
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=documents.models.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "txt", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("txt", "Text"),
                            ("docx", "Word Document"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Document summary", null=True
                    ),
                ),
                (
                    "key_points",
                    models.JSONField(
                        blank=True, help_text="List of key points", null=True
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Sentiment confidence score (0-1)",
                        null=True,
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        blank=True, help_text="List of identified topics", null=True
                    ),
                ),
                ("model_used", models.CharField(default="gemini-pro", max_length=100)),
                (
                    "total_tokens_used",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Total processing time in seconds",
                        null=True,
                    ),
                ),
                ("summary_completed", models.BooleanField(default=False)),
                ("key_points_completed", models.BooleanField(default=False)),
                ("sentiment_completed", models.BooleanField(default=False)),
                ("topics_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTagging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(default=1.0, help_text="Tag confidence (0-1)"),
                ),
                (
                    "auto_generated",
                    models.BooleanField(
                        default=False, help_text="Whether tag was auto-generated by AI"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.documenttag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("celery_task_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("started", "Started"),
                            ("progress", "In Progress"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("retry", "Retry"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("text_extraction_completed", models.BooleanField(default=False)),
                ("ai_analysis_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_job",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "step",
                    models.CharField(
                        blank=True, help_text="Processing step name", max_length=100
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional log metadata", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="documents.document",
                    ),
                ),
                (
                    "processing_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="documents.processingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["user", "-created_at"], name="documents_d_user_id_a8f8c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="documents_d_status_07369e_idx"),
        ),
        migrations.AddIndex(
            model_name="documentanalysis",
            index=models.Index(
                fields=["document"], name="documents_d_documen_a00a00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentanalysis",
            index=models.Index(
                fields=["sentiment"], name="documents_d_sentime_e85d00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttagging",
            index=models.Index(
                fields=["document"], name="documents_d_documen_1f262c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttagging",
            index=models.Index(fields=["tag"], name="documents_d_tag_id_16e4cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documenttagging",
            unique_together={("document", "tag")},
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["celery_task_id"], name="documents_p_celery__ca6da4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["status"], name="documents_p_status_e8fe8e_idx"),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["document", "-created_at"],
                name="documents_p_documen_7d206c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["processing_job", "-created_at"],
                name="documents_p_process_6a6ee4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(fields=["level"], name="documents_p_level_da1822_idx"),
        ),
    ]
